apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: backend
          image: fullstack-backend:latest
          imagePullPolicy: Never   # use local minikube image
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
